ls:
  .dir: snake_case
  .*: snake_case
  .md: snake_case | regex:[0-9A-Z\-]+
  .txt: snake_case
  .yml: snake_case

ignore:
  - .ls-lint.yml
  - .markdownlint.yml
  - .git
  - .github
  - .vscode
  - venv
  - .ruff_cache
  - .pytest_cache
  - __pycache__

    # Ignore generated model + prediction files
  - "4_data_analysis/model_random_forest.joblib"
  - "4_data_analysis/models/pipeline_random_forest.joblib"
  - "4_data_analysis/notebook2_outputs/pipeline_final_rf.joblib"
  - "4_data_analysis/pipeline_regression_rf.joblib"
  - "4_data_analysis/predictions/feature_importances_rf.csv"
  - "4_data_analysis/predictions/predictions_rf.csv"
